<?php include 'nav-not-fixed.php' ?>

  <div class="container" style="padding:50px 140px;text-align:justify;">
    <div class="row">
      <div class="col-lg-12">
        <h1 style="text-align:center">Terms & Conditions</h1>
        <p>Juanderpool Inc is founded on May 2016 by Glenwin Bernabe, Jason Lopez, and Joyce Potestades who’s graduating student of Information Technology at Technological Institute of the Philippines - Manila. Jason is having a hard time in booking a private pool that will suit their family’s budget and needs. The only means of communicating with private pool is through social media platforms and listing sites where you need to contact them individually which is not a secure way to transact your booking. You need to trust a stranger and pay them the specific amount so they’ll be able to reserve the private pool in the given schedule.</p>
        <p>Because of these problems, he pitched his ideas to his classmates and they decided to create an application that will be the solution to eliminate the old ways of booking a private pool here in the Philippines.</p>
        <p>On October 2016, the founders joined Eureka!thon Y which is the corporate incubation program of the PJ Lhullier Group of Companies as spearheaded by its ICT Arm, Networld Capital Ventures, Inc. They won the contest and were given the opportunity to have the full support in establishing their own start up business. </p>
        <p>They believe that vacation experience doesn’t begin in the swimming pool but the experience should rather start in choosing a private pool and ends with giving their feedback about their amazing experience.</p>
        <p>These terms and conditions, as may be amended from time to time, apply to all our services directly or indirectly (through distributors) made available online, through any mobile device, by email or by telephone. By accessing, browsing and using our (mobile) website or any of our applications through whatever platform (hereafter collectively referred to as the "website") and/or by completing a reservation, you acknowledge and agree to have read, understood and agreed to the terms and conditions set out below (including the privacy statement).</p>
        <p>These pages, the content and infrastructure of these pages, and the online reservation service provided on these pages and through the website are owned, operated and provided by Booking.com B.V. and are provided for your personal, non-commercial use only, subject to the terms and conditions set out below.</p>
        <p>Through the Platform, we (Booking.com B.V. and its affiliate (distribution) partners) provide an online platform through which Suppliers can advertise their products and service for reservation, and through which visitors of the Platform can make such reservations (i.e. the reservation service). By making a reservation through Booking.com, you enter into a direct (legally binding) contractual relationship with the Supplier with which you make a reservation or purchase a product or service (as applicable). From the point at which you make your reservation, we act solely as an intermediary between you and the Supplier, transmitting the details of your reservation to the relevant Supplier(s) and sending you a confirmation email for and on behalf of the Supplier.</p>
      </div>
    </div>
  </div>
        <?php include 'footer-not-fixed.php' ?>
